update @ 2023-10-23 08:16:22 UTC
### 3sat

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1058, in _validate_conn
    conn.connect()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/urllib3/connection.py", line 472, in connect
    _match_hostname(cert, self.assert_hostname or server_hostname)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/urllib3/connection.py", line 545, in _match_hostname
    match_hostname(cert, asserted_hostname)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/urllib3/util/ssl_match_hostname.py", line 150, in match_hostname
    raise CertificateError(
urllib3.util.ssl_match_hostname.CertificateError: hostname 'blog.3sat.de' doesn't match either of '*.zdf.de', 'zdf.de'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='blog.3sat.de', port=443): Max retries exceeded with url: /ttx/index.php?p=100_0001&c=0 (Caused by SSLError(CertificateError("hostname 'blog.3sat.de' doesn't match either of '*.zdf.de', 'zdf.de'")))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/teletext-archive-2023/teletext-archive-2023/src/scraper.py", line 186, in get_html
    return self.session.request(method=method, url=url, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='blog.3sat.de', port=443): Max retries exceeded with url: /ttx/index.php?p=100_0001&c=0 (Caused by SSLError(CertificateError("hostname 'blog.3sat.de' doesn't match either of '*.zdf.de', 'zdf.de'")))
```
### ard

- 350 pages changed
- 26 pages added
- 31 pages removed
- 677 pages unchanged

### ndr

- 315 pages changed
- 16 pages added
- 22 pages removed
- 913 pages unchanged

### ntv

- 591 pages changed
- 7 pages added
- 20 pages removed
- 311 pages unchanged

### sr

- 118 pages changed
- 6 pages added
- 10 pages removed
- 358 pages unchanged

### wdr

```
Traceback (most recent call last):
  File "update.py", line 42, in scrape
    report = scraper.download()
  File "/home/runner/work/teletext-archive-2023/teletext-archive-2023/src/scraper.py", line 129, in download
    for page_num, sub_page_num, content in self.iter_pages():
  File "/home/runner/work/teletext-archive-2023/teletext-archive-2023/src/sources/wdr.py", line 58, in iter_pages
    for sub_index, content in self._iter_sub_pages(soup.find("div", {"id": "wdrtext_inner"})):
  File "/home/runner/work/teletext-archive-2023/teletext-archive-2023/src/sources/wdr.py", line 63, in _iter_sub_pages
    sub_page = div.find("div", {"id": f"seite_{sub_index}"})
AttributeError: 'NoneType' object has no attribute 'find'
```
### zdf

- 356 pages changed
- 244 pages added
- 72 pages removed
- 378 pages unchanged

### zdf-info

- 298 pages changed
- 218 pages added
- 25 pages removed
- 79 pages unchanged

### zdf-neo

- 206 pages changed
- 56 pages added
- 15 pages removed
- 69 pages unchanged