update @ 2023-10-08 00:56:03 UTC
### 3sat

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/urllib3/connection.py", line 472, in connect
    _match_hostname(cert, self.assert_hostname or server_hostname)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/urllib3/connection.py", line 545, in _match_hostname
    match_hostname(cert, asserted_hostname)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/urllib3/util/ssl_match_hostname.py", line 150, in match_hostname
    raise CertificateError(
urllib3.util.ssl_match_hostname.CertificateError: hostname 'blog.3sat.de' doesn't match either of '*.zdf.de', 'zdf.de'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='blog.3sat.de', port=443): Max retries exceeded with url: /ttx/index.php?p=100_0001&c=0 (Caused by SSLError(CertificateError("hostname 'blog.3sat.de' doesn't match either of '*.zdf.de', 'zdf.de'")))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/teletext-archive-2023/teletext-archive-2023/src/scraper.py", line 186, in get_html
    return self.session.request(method=method, url=url, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='blog.3sat.de', port=443): Max retries exceeded with url: /ttx/index.php?p=100_0001&c=0 (Caused by SSLError(CertificateError("hostname 'blog.3sat.de' doesn't match either of '*.zdf.de', 'zdf.de'")))
```
### ard

- 245 pages changed
- 31 pages added
- 11 pages removed
- 943 pages unchanged

### ndr

- 388 pages changed
- 22 pages added
- 10 pages removed
- 858 pages unchanged

### ntv

- 414 pages changed
- 4 pages added
- 505 pages unchanged

### sr

- 140 pages changed
- 4 pages added
- 2 pages removed
- 325 pages unchanged

### wdr

- 325 pages changed
- 20 pages added
- 14 pages removed
- 707 pages unchanged

### zdf

- 237 pages changed
- 25 pages added
- 20 pages removed
- 531 pages unchanged

### zdf-info

- 123 pages changed
- 5 pages added
- 6 pages removed
- 294 pages unchanged

### zdf-neo

- 101 pages changed
- 4 pages added
- 6 pages removed
- 188 pages unchanged